[project]
name = "pytest-sources"
version = "0.1.0"
description = "pytest plugin for running tests on multiple different source code"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "Dan Nguyen", email = "dan@tuppl.dev" }]
dependencies = [
  "pytest>=9.1.1",
]

[project.entry-points.pytest11]
sources = "pytest_sources.plugin"

[dependency-groups]
dev = [
  "ruff>=0.16.1",
]

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120
